//! Workspace bridge — the launcher-owned link between the user's strategy
//! Workspace and the local engine.
//!
//! On first install the launcher:
//!   1. seeds a canonical Workspace ("Auracle Strategies" under the per-OS
//!      documents dir) with six Canonical folders, a one-line README in
//!      each, a root README, and a Scripts marker in `Analysis/`;
//!   2. writes a launcher-owned `docker-compose.override.yml` into the
//!      engine home that mounts that Workspace into the engine's strategy
//!      discovery path (`/opt/auracle/strategies/desk`); and
//!   3. records the Workspace path in the provisioning config
//!      (`~/.config/auracle/auracle.json`) — the single source of truth the
//!      IDE consumes in a follow-up slice.
//!
//! Two ownership/heal laws, mirroring the stack-collision guard in
//! `docker.rs`:
//!   * The override carries an ownership-marker header. The launcher only
//!     creates / heals / rewrites overrides it owns. A pre-existing override
//!     it does NOT own (a hand-built setup) is adopted-or-aborted — left
//!     untouched and reported (`OverrideStatus::ForeignPreserved`).
//!   * Configuration (the override) heals on stack start when missing. User
//!     content (the seeded folders) is seeded ONCE and thereafter recreated
//!     only on demand by system write paths (`ensure_folder`) — never
//!     resurrected at launch.
//!
//! All filesystem writes in this module are additive-only: `seed_workspace`
//! never overwrites or deletes an existing file, and `write_override` never
//! clobbers a foreign file.
//!
//! Testability: the path-resolving entry points read an env override then
//! fall back to the per-OS default (the `resolve_install_path` precedent in
//! `installer.rs`), and every worker takes an explicit base path so the unit
//! tests drive them entirely over temp directories — nothing here touches a
//! real home / documents dir during tests.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

/// Canonical Workspace directory name, created under the documents dir.
const WORKSPACE_DIR_NAME: &str = "Auracle Strategies";

/// Env override for the Workspace root — dev / power-user relocation and the
/// injectable base for any integration test. Mirrors `AURACLE_INSTALL_DIR`.
const WORKSPACE_DIR_ENV: &str = "AURACLE_WORKSPACE_DIR";

/// The launcher-owned compose override filename, dropped into the engine
/// home. Docker Compose auto-loads it alongside `docker-compose.yml`.
const OVERRIDE_FILENAME: &str = "docker-compose.override.yml";

/// First line of a launcher-owned override. Presence of this exact marker on
/// the first line is how `is_launcher_owned` tells our file apart from a
/// hand-built one; removing the line hands manual ownership back to the user.
const OWNERSHIP_MARKER: &str =
    "# auracle-desktop managed override v1 - regenerated by the launcher; \
manual edits will be preserved only by removing this line";

/// Engine-side mount target the override binds the Workspace to. Houston +
/// the scheduler discover strategies under `/opt/auracle/strategies`; the
/// Workspace grafts in at the `desk` subdir (deploy path
/// `strategies.desk.<...>`).
const MOUNT_TARGET: &str = "/opt/auracle/strategies/desk";

/// Filename of the engine's base compose, in the engine home. Matches
/// `installer::is_installed`'s probe. We read it to learn which services
/// actually exist before mounting the Workspace into any of them.
const BASE_COMPOSE_FILENAME: &str = "docker-compose.yml";

/// Desired Workspace consumers and their access mode, in emit order. A mount
/// is written ONLY for a service the base compose actually defines (see
/// `render_override`) — adding a volume to a service the base doesn't declare
/// makes `docker compose up` fail on an imageless service. houston + mcp
/// author strategy sources (rw); the scheduler + live-supervisor runners and
/// jupyter (which reads notebooks) get it read-only.
const DESIRED_MOUNTS: &[(&str, &str)] = &[
    ("houston", "rw"),
    ("mcp", "rw"),
    ("scheduler", "ro"),
    ("live-supervisor", "ro"),
    ("jupyter", "ro"),
];

/// The six Canonical folders and their one-line README bodies, in seed order.
/// `Analysis` is last so the Scripts marker write follows its creation.
const CANONICAL_FOLDERS: &[(&str, &str)] = &[
    (
        "Potential",
        "Working drafts and research candidates. Start here.",
    ),
    ("Live", "Strategies currently deployed to paper or live."),
    (
        "Tearsheets",
        "Generated pitch PDFs and reports (output - read-only).",
    ),
    ("Testing", "Scratch experiments."),
    ("Trashed", "Soft-deleted strategies. Safe to ignore."),
    (
        "Analysis",
        "Analysis scripts, helper functions, and notebooks - not strategies; \
never backtested or deployed.",
    ),
];

/// Marker file placed in `Analysis/` so system write paths and the engine
/// treat that folder as code, not strategies.
const NO_STRATEGIES_MARKER: &str = ".no-strategies";
const NO_STRATEGIES_BODY: &str =
    "# Analysis holds helper code, not strategies. The engine skips it for \
strategy discovery.\n";

// ─── Path resolution (env-injectable, per-OS defaults) ──────────────────────

/// Home dir the same way the rest of the launcher resolves it: the `HOME` /
/// `USERPROFILE` env directly (see `installer::dirs_home`), never the
/// deprecated `std::env::home_dir`.
fn home_dir() -> anyhow::Result<PathBuf> {
    if cfg!(windows) {
        std::env::var("USERPROFILE")
            .map(PathBuf::from)
            .map_err(|_| anyhow::anyhow!("USERPROFILE env var not set"))
    } else {
        std::env::var("HOME")
            .map(PathBuf::from)
            .map_err(|_| anyhow::anyhow!("HOME env var not set"))
    }
}

/// Per-OS user documents directory (`~/Documents`).
fn documents_dir() -> anyhow::Result<PathBuf> {
    Ok(home_dir()?.join("Documents"))
}

/// Resolve the canonical Workspace path — the `AURACLE_WORKSPACE_DIR` env
/// override (dev / power-user / test), else `<documents>/Auracle Strategies`.
pub fn canonical_workspace_path() -> anyhow::Result<PathBuf> {
    if let Ok(p) = std::env::var(WORKSPACE_DIR_ENV) {
        let p = p.trim();
        if !p.is_empty() {
            return Ok(PathBuf::from(p));
        }
    }
    Ok(documents_dir()?.join(WORKSPACE_DIR_NAME))
}

/// Path of the launcher's provisioning config (`~/.config/auracle/auracle.json`)
/// — the file the IDE reads for `{engine_url, api_key, workspace_path}`.
pub fn provisioning_config_path() -> anyhow::Result<PathBuf> {
    Ok(home_dir()?
        .join(".config")
        .join("auracle")
        .join("auracle.json"))
}

// ─── Workspace seeding (user content — seed once, additive-only) ────────────

/// Seed the canonical Workspace at `root`: create the Workspace dir, the six
/// Canonical folders, a one-line README in each, a root README, and the
/// Scripts marker in `Analysis/`. Idempotent and additive-only — an existing
/// file is never overwritten, moved, or deleted, so re-running produces the
/// identical tree and leaves existing files (and their mtimes) untouched.
pub fn seed_workspace(root: &Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(root)?;
    write_if_absent(&root.join("README.md"), &render_root_readme())?;
    for (name, desc) in CANONICAL_FOLDERS {
        // Share the create-on-demand seam so folder creation has one home.
        let dir = ensure_folder(root, name)?;
        write_if_absent(&dir.join("README.md"), &format!("{desc}\n"))?;
    }
    write_if_absent(
        &root.join("Analysis").join(NO_STRATEGIES_MARKER),
        NO_STRATEGIES_BODY,
    )?;
    Ok(())
}

/// Create-on-demand helper for system write paths: ensure `<root>/<name>`
/// exists, returning its path. Idempotent. This — NOT `seed_workspace` — is
/// how a Canonical folder a user deleted comes back: only when something is
/// about to write into it, never resurrected at launch.
pub fn ensure_folder(root: &Path, name: &str) -> anyhow::Result<PathBuf> {
    let dir = root.join(name);
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

/// Write `contents` to `path` only if the file does not already exist. The
/// additive-only primitive behind `seed_workspace`.
fn write_if_absent(path: &Path, contents: &str) -> anyhow::Result<()> {
    if path.exists() {
        return Ok(());
    }
    std::fs::write(path, contents)?;
    Ok(())
}

/// Root README: the workspace headline plus one line per Canonical folder.
fn render_root_readme() -> String {
    use std::fmt::Write;
    let mut s =
        String::from("# Auracle Strategies\n\nThis is your Auracle strategy workspace.\n\n");
    for (name, desc) in CANONICAL_FOLDERS {
        let _ = writeln!(s, "- {name}/ - {desc}");
    }
    s
}

// ─── Compose override (configuration — launcher-owned, heals on start) ──────

/// Outcome of `write_override`, surfaced by the caller (logged / shown).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OverrideStatus {
    /// No override existed — one was created.
    Written,
    /// A launcher-owned override existed but had drifted — regenerated.
    Rewritten,
    /// A launcher-owned override existed and already matched — left as-is.
    Unchanged,
    /// A hand-built override we do NOT own existed — left untouched
    /// (adopt-or-abort), so an existing bespoke setup is safe.
    ForeignPreserved,
    /// The engine's base compose defines no recognized read-write consumer
    /// (neither houston nor mcp) — an unknown / degenerate compose. Nothing
    /// was written rather than emit an override that would break the stack.
    SkippedNoConsumers,
}

/// True when `content`'s first line is the launcher's ownership marker — the
/// signal that the launcher may heal / rewrite / remove this override.
pub fn is_launcher_owned(content: &str) -> bool {
    content.lines().next().map(str::trim) == Some(OWNERSHIP_MARKER)
}

/// Render the launcher-owned override that mounts `workspace_path` into the
/// engine at `/opt/auracle/strategies/desk`, emitting a mount ONLY for a
/// desired consumer (`DESIRED_MOUNTS`) that `services_present` actually
/// contains — never for a service the base compose doesn't define (that would
/// make `docker compose up` fail on an imageless service). First line is the
/// ownership marker.
///
/// Returns `None` when the present services include no read-write consumer
/// (neither houston nor mcp) — an unknown / degenerate compose we refuse to
/// write a mount into rather than emit a broken override.
pub fn render_override(
    services_present: &BTreeSet<String>,
    workspace_path: &Path,
) -> Option<String> {
    use std::fmt::Write;

    let mounts: Vec<(&str, &str)> = DESIRED_MOUNTS
        .iter()
        .copied()
        .filter(|(svc, _)| services_present.contains(*svc))
        .collect();

    // Without a read-write consumer (houston or mcp) this isn't a compose we
    // recognize — refuse rather than emit a degenerate override.
    if !mounts.iter().any(|&(_, mode)| mode == "rw") {
        return None;
    }

    let ws = workspace_path.to_string_lossy();
    let mount = |mode: &str| yaml_quote(&format!("{ws}:{MOUNT_TARGET}:{mode}"));

    let mut s = String::new();
    let _ = writeln!(s, "{OWNERSHIP_MARKER}");
    let _ = writeln!(
        s,
        "# Managed by Auracle Desktop: mounts your Workspace into the engine so"
    );
    let _ = writeln!(
        s,
        "# strategies placed there are discovered. To hand-manage this stack,"
    );
    let _ = writeln!(
        s,
        "# delete the first line above and the launcher will leave this file alone."
    );
    let _ = writeln!(s, "services:");
    for (svc, mode) in mounts {
        let _ = writeln!(s, "  {svc}:");
        let _ = writeln!(s, "    volumes:");
        let _ = writeln!(s, "      - {}", mount(mode));
    }
    Some(s)
}

/// Parse the top-level service names out of a compose file's contents. A
/// light line-scan (the repo carries no YAML crate, and pulling one in for one
/// field-set of names isn't worth it): a service is a key indented exactly two
/// spaces under the top-level `services:` block. Nested keys (4+ spaces),
/// comments, and blank lines are ignored; any other top-level key closes the
/// block.
fn parse_compose_service_names(compose: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let mut in_services = false;
    for line in compose.lines() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let indent = line.len() - trimmed.len();
        if indent == 0 {
            // A top-level key: `services:` opens the block; anything else
            // (volumes:, networks:, name:, …) closes it.
            in_services = trimmed.starts_with("services:");
            continue;
        }
        if in_services && indent == 2 {
            if let Some(name) = trimmed.split(':').next() {
                let name = name.trim();
                if !name.is_empty() {
                    names.insert(name.to_string());
                }
            }
        }
    }
    names
}

/// Read the engine's base compose from `engine_home` and return the service
/// names it defines. An unreadable / missing compose yields an empty set — the
/// caller then treats it as a degenerate compose and writes no override.
fn read_base_compose_services(engine_home: &Path) -> BTreeSet<String> {
    match std::fs::read_to_string(engine_home.join(BASE_COMPOSE_FILENAME)) {
        Ok(contents) => parse_compose_service_names(&contents),
        Err(_) => BTreeSet::new(),
    }
}

/// Write / heal the launcher-owned override in `engine_home` for
/// `workspace_path`. The mounts are derived from the services the engine's
/// base compose actually defines (`read_base_compose_services`). Never
/// clobbers a foreign file:
///   * base has no rw consumer        → write nothing        (`SkippedNoConsumers`)
///   * no override present            → write it             (`Written`)
///   * present, launcher-owned, drift → regenerate           (`Rewritten`)
///   * present, launcher-owned, same  → no write             (`Unchanged`)
///   * present, NOT launcher-owned    → leave it             (`ForeignPreserved`)
///
/// A non-UTF-8 / unreadable existing override file surfaces as `Err`
/// (fail-safe: the best-effort callers log and continue without touching it).
pub fn write_override(engine_home: &Path, workspace_path: &Path) -> anyhow::Result<OverrideStatus> {
    let services = read_base_compose_services(engine_home);
    let desired = match render_override(&services, workspace_path) {
        Some(desired) => desired,
        None => return Ok(OverrideStatus::SkippedNoConsumers),
    };
    let path = engine_home.join(OVERRIDE_FILENAME);
    match std::fs::read_to_string(&path) {
        Ok(existing) => {
            if !is_launcher_owned(&existing) {
                return Ok(OverrideStatus::ForeignPreserved);
            }
            if existing == desired {
                return Ok(OverrideStatus::Unchanged);
            }
            std::fs::create_dir_all(engine_home)?;
            std::fs::write(&path, desired)?;
            Ok(OverrideStatus::Rewritten)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            std::fs::create_dir_all(engine_home)?;
            std::fs::write(&path, desired)?;
            Ok(OverrideStatus::Written)
        }
        Err(e) => Err(e.into()),
    }
}

/// Double-quoted YAML scalar, escaping the two characters that would break
/// the quoting (`\` then `"`). Workspace paths under the documents dir carry
/// spaces ("Auracle Strategies"); a double-quoted scalar handles those.
fn yaml_quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

// ─── Provisioning config (workspace_path — launcher is the single writer) ───

/// Merge a provisioning-config write. `engine_url` / `api_key`, when
/// supplied, are REFRESHED (the IDE handoff rotates them); `workspace_path`,
/// when supplied, is inserted only when ABSENT so a value the user or a prior
/// first-install already set is never overwritten. Any other keys already in
/// the file are preserved. A corrupt / non-object existing file is replaced
/// rather than failing provisioning (its keys are re-supplied by the caller).
pub fn merge_provisioning_config(
    existing: Option<&str>,
    engine_url: Option<&str>,
    api_key: Option<&str>,
    workspace_path: Option<&str>,
) -> anyhow::Result<String> {
    let mut obj: Map<String, Value> = match existing {
        Some(s) if !s.trim().is_empty() => match serde_json::from_str::<Value>(s) {
            Ok(Value::Object(m)) => m,
            _ => Map::new(),
        },
        _ => Map::new(),
    };
    if let Some(u) = engine_url {
        obj.insert("engine_url".to_string(), Value::String(u.to_string()));
    }
    if let Some(k) = api_key {
        obj.insert("api_key".to_string(), Value::String(k.to_string()));
    }
    if let Some(w) = workspace_path {
        obj.entry("workspace_path".to_string())
            .or_insert_with(|| Value::String(w.to_string()));
    }
    Ok(serde_json::to_string_pretty(&Value::Object(obj))?)
}

/// Read the `workspace_path` field out of provisioning-config text.
fn parse_workspace_path(content: &str) -> Option<String> {
    let v: Value = serde_json::from_str(content).ok()?;
    v.get("workspace_path")?.as_str().map(str::to_string)
}

/// Persist `workspace_path` into the config at `config_path`, inserting it
/// only when absent and preserving every other key. Creates the parent dir
/// and locks the file to owner-only (it later carries the per-user API key).
pub fn persist_workspace_path_to(config_path: &Path, workspace_path: &Path) -> anyhow::Result<()> {
    let existing = std::fs::read_to_string(config_path).ok();
    let ws = workspace_path.to_string_lossy();
    let merged = merge_provisioning_config(existing.as_deref(), None, None, Some(&ws))?;
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(config_path, merged)?;
    set_owner_only(config_path);
    Ok(())
}

/// Persist the Workspace path into the default provisioning config.
pub fn persist_workspace_path(workspace_path: &Path) -> anyhow::Result<()> {
    persist_workspace_path_to(&provisioning_config_path()?, workspace_path)
}

/// Read the persisted Workspace path from the config at `config_path`.
pub fn read_workspace_path_from(config_path: &Path) -> Option<PathBuf> {
    let content = std::fs::read_to_string(config_path).ok()?;
    parse_workspace_path(&content).map(PathBuf::from)
}

/// Read the persisted Workspace path from the default provisioning config —
/// the accessor `stack_start` uses to know whether to heal the override.
pub fn persisted_workspace_path() -> Option<PathBuf> {
    let path = provisioning_config_path().ok()?;
    read_workspace_path_from(&path)
}

/// chmod 0600 (best-effort, unix only) — the config later holds the API key.
fn set_owner_only(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
}

// ─── First-install orchestration (best-effort — never fails the install) ────

/// Best-effort first-install Workspace bridge: seed the canonical Workspace,
/// write the launcher-owned compose override into `engine_home`, and record
/// the Workspace path in the provisioning config. Every step is logged and
/// NONE can fail the install — consistent with how the launcher treats other
/// best-effort post-install steps (tray / health). Folders are seeded here
/// once; they are never re-seeded at launch.
pub fn provision_on_first_install(engine_home: &Path) {
    let workspace = match canonical_workspace_path() {
        Ok(w) => w,
        Err(e) => {
            log::warn!("workspace bridge: can't resolve the Workspace path ({e}); skipping");
            return;
        }
    };
    match seed_workspace(&workspace) {
        Ok(()) => log::info!(
            "workspace bridge: seeded Workspace at {}",
            workspace.display()
        ),
        Err(e) => log::warn!("workspace bridge: seeding failed ({e}); continuing"),
    }
    match write_override(engine_home, &workspace) {
        Ok(OverrideStatus::ForeignPreserved) => log::warn!(
            "workspace bridge: an existing docker-compose.override.yml in {} isn't \
             launcher-owned — left untouched; the Workspace mount was not added",
            engine_home.display()
        ),
        Ok(OverrideStatus::SkippedNoConsumers) => log::warn!(
            "workspace bridge: the engine's base compose in {} defines no recognized \
             strategy consumer (houston/mcp) — skipped writing the Workspace mount",
            engine_home.display()
        ),
        Ok(status) => log::info!("workspace bridge: override {status:?}"),
        Err(e) => log::warn!("workspace bridge: override write failed ({e}); continuing"),
    }
    if let Err(e) = persist_workspace_path(&workspace) {
        log::warn!("workspace bridge: recording the Workspace path failed ({e}); continuing");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    static COUNTER: AtomicU32 = AtomicU32::new(0);

    /// Per-process-unique scratch dir so parallel `cargo test` runs (and any
    /// leftover from a crashed run) can't collide. Nothing here touches a real
    /// home / documents / config dir.
    fn scratch() -> PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir =
            std::env::temp_dir().join(format!("auracle-workspace-test-{}-{n}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("scratch dir");
        dir
    }

    fn read(path: &Path) -> String {
        std::fs::read_to_string(path).expect("read")
    }

    // ── seeding ──────────────────────────────────────────────────────────

    #[test]
    fn seed_creates_full_tree() {
        let root = scratch();
        let ws = root.join("Auracle Strategies");
        seed_workspace(&ws).expect("seed");

        assert!(ws.join("README.md").exists(), "root README");
        assert!(read(&ws.join("README.md")).contains("This is your Auracle strategy workspace."));
        for (name, desc) in CANONICAL_FOLDERS {
            let dir = ws.join(name);
            assert!(dir.is_dir(), "folder {name} exists");
            let readme = dir.join("README.md");
            assert!(readme.exists(), "{name}/README.md exists");
            assert_eq!(read(&readme), format!("{desc}\n"), "{name} one-liner");
        }
        // Exactly the six Canonical folders — no extras.
        assert_eq!(CANONICAL_FOLDERS.len(), 6);

        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn seed_creates_analysis_marker() {
        let root = scratch();
        seed_workspace(&root).expect("seed");
        let marker = root.join("Analysis").join(".no-strategies");
        assert!(marker.exists(), "Analysis/.no-strategies exists");
        assert_eq!(read(&marker), NO_STRATEGIES_BODY);
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn seed_is_idempotent_and_preserves_mtimes() {
        let root = scratch();
        seed_workspace(&root).expect("first seed");

        // Snapshot the file set + the root README mtime.
        let readme = root.join("README.md");
        let mtime_before = std::fs::metadata(&readme).unwrap().modified().unwrap();
        let listing_before = walk(&root);

        seed_workspace(&root).expect("second seed");

        let mtime_after = std::fs::metadata(&readme).unwrap().modified().unwrap();
        let listing_after = walk(&root);
        assert_eq!(mtime_before, mtime_after, "existing file mtime untouched");
        assert_eq!(
            listing_before, listing_after,
            "tree identical after re-seed"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn seed_never_clobbers_existing_readme() {
        let root = scratch();
        // A user already edited Potential/README.md before the seed runs.
        let potential = root.join("Potential");
        std::fs::create_dir_all(&potential).unwrap();
        let readme = potential.join("README.md");
        std::fs::write(&readme, "MY OWN NOTES - keep me\n").unwrap();

        seed_workspace(&root).expect("seed");

        assert_eq!(
            read(&readme),
            "MY OWN NOTES - keep me\n",
            "user content preserved"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn ensure_folder_creates_on_demand() {
        let root = scratch();
        // No seed — ensure_folder stands alone as the create-on-demand path.
        let made = ensure_folder(&root, "Live").expect("ensure");
        assert!(made.is_dir());
        assert_eq!(made, root.join("Live"));
        // Idempotent: a second call over an existing dir is fine.
        ensure_folder(&root, "Live").expect("ensure again");
        let _ = std::fs::remove_dir_all(&root);
    }

    // ── ownership marker ────────────────────────────────────────────────

    #[test]
    fn is_launcher_owned_detects_marker() {
        let services = services_set(&["houston", "mcp"]);
        let owned = render_override(&services, Path::new("/tmp/ws")).expect("render");
        assert!(is_launcher_owned(&owned), "our own render is owned");
        assert!(is_launcher_owned(&format!(
            "{OWNERSHIP_MARKER}\nservices:\n"
        )));
        // Hand-built files and empties are not ours.
        assert!(!is_launcher_owned("services:\n  houston:\n"));
        assert!(!is_launcher_owned(""));
        // Marker present but NOT on the first line → not owned.
        assert!(!is_launcher_owned(&format!(
            "services:\n{OWNERSHIP_MARKER}\n"
        )));
    }

    #[test]
    fn render_marker_desk_target_and_rw_ro_split() {
        // A base that has every desired consumer EXCEPT live-supervisor.
        let services = services_set(&["houston", "mcp", "scheduler", "jupyter", "db"]);
        let content = render_override(
            &services,
            Path::new("/Users/x/Documents/Auracle Strategies"),
        )
        .expect("render");
        assert_eq!(
            content.lines().next().map(str::trim),
            Some(OWNERSHIP_MARKER),
            "marker is the first line"
        );
        // All mounts land at the desk target; rw for authors, ro for readers.
        assert!(content
            .contains("\"/Users/x/Documents/Auracle Strategies:/opt/auracle/strategies/desk:rw\""));
        assert!(content
            .contains("\"/Users/x/Documents/Auracle Strategies:/opt/auracle/strategies/desk:ro\""));
        assert_eq!(mode_for(&content, "houston"), "rw", "houston rw");
        assert_eq!(mode_for(&content, "mcp"), "rw", "mcp rw");
        assert_eq!(mode_for(&content, "scheduler"), "ro", "scheduler ro");
        assert_eq!(mode_for(&content, "jupyter"), "ro", "jupyter ro");
    }

    #[test]
    fn render_includes_only_present_services() {
        // live-supervisor is NOT in this base compose → must be absent from the
        // override (the whole point of the fix: no imageless-service mount).
        let services = services_set(&["houston", "mcp", "scheduler", "jupyter"]);
        let content = render_override(&services, Path::new("/ws")).expect("render");
        for svc in ["houston", "mcp", "scheduler", "jupyter"] {
            assert!(content.contains(&format!("  {svc}:")), "{svc} present");
        }
        assert!(
            !content.contains("live-supervisor"),
            "absent service must not be mounted"
        );
        // db is present in the base but not a desired consumer → not mounted.
        assert!(
            !content.contains("  db:"),
            "non-consumer service not mounted"
        );
    }

    #[test]
    fn render_returns_none_without_rw_consumer() {
        // Neither houston nor mcp present → degenerate compose → no override.
        let services = services_set(&["scheduler", "live-supervisor", "jupyter", "db"]);
        assert!(render_override(&services, Path::new("/ws")).is_none());
        // Truly empty service set → also None.
        assert!(render_override(&BTreeSet::new(), Path::new("/ws")).is_none());
        // A single rw consumer is enough to render.
        assert!(render_override(&services_set(&["mcp"]), Path::new("/ws")).is_some());
    }

    #[test]
    fn parse_compose_service_names_finds_top_level_services() {
        // Realistic shape: `name:` before services, comments, 4-space sub-keys,
        // 6-space list items, then a `volumes:` top-level key that closes the
        // block. Only the 2-space service keys should come back.
        let compose = "\
name: auracle

services:
  db:
    image: timescale/timescaledb:latest
    # a comment inside a service
    volumes:
      - db-data:/var/lib/postgresql/data
  houston:
    image: siixquant/auracle-houston:latest
    volumes:
      - ./strategies:/opt/auracle/strategies:rw
  scheduler:
    image: siixquant/auracle-scheduler:latest
volumes:
  db-data:
networks:
  auraclenet:
";
        let names = parse_compose_service_names(compose);
        assert_eq!(
            names,
            services_set(&["db", "houston", "scheduler"]),
            "exactly the top-level services, not volumes/networks/nested keys"
        );
    }

    // ── write_override: absent / owned-drift / owned-same / foreign ──────

    #[test]
    fn write_override_writes_when_absent() {
        let home = scratch();
        write_base_compose(&home, &["houston", "mcp", "scheduler", "jupyter"]);
        let status = write_override(&home, Path::new("/ws")).expect("write");
        assert_eq!(status, OverrideStatus::Written);
        let content = read(&home.join("docker-compose.override.yml"));
        assert!(is_launcher_owned(&content), "written file is owned");
        // Mounts reflect the base compose — no live-supervisor (absent there).
        assert!(content.contains("  houston:") && content.contains("  jupyter:"));
        assert!(
            !content.contains("live-supervisor"),
            "absent service not mounted"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn write_override_rewrites_owned_drift() {
        let home = scratch();
        write_base_compose(&home, &["houston", "mcp", "scheduler"]);
        // Seed an owned override pointing at an OLD workspace, then heal to a new one.
        write_override(&home, Path::new("/old/ws")).expect("write old");
        let status = write_override(&home, Path::new("/new/ws")).expect("rewrite");
        assert_eq!(status, OverrideStatus::Rewritten);
        let content = read(&home.join("docker-compose.override.yml"));
        assert!(
            content.contains("/new/ws:"),
            "content updated to new workspace"
        );
        assert!(!content.contains("/old/ws:"), "old workspace gone");
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn write_override_unchanged_when_identical() {
        let home = scratch();
        write_base_compose(&home, &["houston", "mcp", "scheduler"]);
        write_override(&home, Path::new("/ws")).expect("write");
        let path = home.join("docker-compose.override.yml");
        let mtime_before = std::fs::metadata(&path).unwrap().modified().unwrap();

        let status = write_override(&home, Path::new("/ws")).expect("second write");
        assert_eq!(status, OverrideStatus::Unchanged);
        let mtime_after = std::fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(
            mtime_before, mtime_after,
            "identical override not rewritten"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn write_override_preserves_foreign() {
        let home = scratch();
        write_base_compose(&home, &["houston", "mcp", "scheduler"]);
        // A hand-built override with NO ownership marker.
        let path = home.join("docker-compose.override.yml");
        let handmade = "services:\n  houston:\n    volumes:\n      - \"/my/own:/opt/auracle/strategies/desk:rw\"\n";
        std::fs::write(&path, handmade).unwrap();

        let status = write_override(&home, Path::new("/ws")).expect("adopt");
        assert_eq!(status, OverrideStatus::ForeignPreserved);
        assert_eq!(
            read(&path),
            handmade,
            "foreign file left byte-for-byte untouched"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn write_override_skips_degenerate_compose() {
        let home = scratch();
        // Base compose with services, but none of the rw consumers (houston/mcp).
        write_base_compose(&home, &["db", "scheduler", "jupyter"]);
        let status = write_override(&home, Path::new("/ws")).expect("skip");
        assert_eq!(status, OverrideStatus::SkippedNoConsumers);
        assert!(
            !home.join("docker-compose.override.yml").exists(),
            "no override written for a degenerate compose"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn write_override_skips_when_base_compose_missing() {
        let home = scratch();
        // No docker-compose.yml at all → we can't learn the services → skip.
        let status = write_override(&home, Path::new("/ws")).expect("skip");
        assert_eq!(status, OverrideStatus::SkippedNoConsumers);
        assert!(!home.join("docker-compose.override.yml").exists());
        let _ = std::fs::remove_dir_all(&home);
    }

    // ── provisioning config: add-not-overwrite + round-trip ──────────────

    #[test]
    fn merge_config_adds_workspace_path_when_absent() {
        // Existing handoff config with just engine_url + api_key.
        let existing = r#"{"engine_url":"http://127.0.0.1:1969","api_key":"secret"}"#;
        let merged = merge_provisioning_config(Some(existing), None, None, Some("/ws")).unwrap();
        let v: Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["workspace_path"], "/ws");
        assert_eq!(
            v["engine_url"], "http://127.0.0.1:1969",
            "engine_url preserved"
        );
        assert_eq!(v["api_key"], "secret", "api_key preserved");
    }

    #[test]
    fn merge_config_never_overwrites_existing_workspace_path() {
        let existing = r#"{"workspace_path":"/user/custom","api_key":"k"}"#;
        // Even though we pass a different path, the existing one wins.
        let merged =
            merge_provisioning_config(Some(existing), None, None, Some("/default")).unwrap();
        let v: Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["workspace_path"], "/user/custom", "user value untouched");
        assert_eq!(v["api_key"], "k");
    }

    #[test]
    fn merge_config_refreshes_keys_and_starts_from_empty() {
        // No existing file: a fresh object carries exactly what we supply.
        let merged = merge_provisioning_config(
            None,
            Some("http://127.0.0.1:1969"),
            Some("newkey"),
            Some("/ws"),
        )
        .unwrap();
        let v: Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["engine_url"], "http://127.0.0.1:1969");
        assert_eq!(v["api_key"], "newkey");
        assert_eq!(v["workspace_path"], "/ws");

        // Corrupt existing content is replaced, not fatal.
        let merged =
            merge_provisioning_config(Some("}{ not json"), None, None, Some("/ws")).unwrap();
        let v: Value = serde_json::from_str(&merged).unwrap();
        assert_eq!(v["workspace_path"], "/ws");
    }

    #[test]
    fn persist_and_read_workspace_path_round_trip() {
        let home = scratch();
        let config = home.join(".config").join("auracle").join("auracle.json");

        persist_workspace_path_to(&config, Path::new("/docs/Auracle Strategies")).expect("persist");
        assert_eq!(
            read_workspace_path_from(&config),
            Some(PathBuf::from("/docs/Auracle Strategies")),
        );

        // Re-persisting a DIFFERENT path must not overwrite the first (single
        // writer, insert-if-absent).
        persist_workspace_path_to(&config, Path::new("/somewhere/else")).expect("persist again");
        assert_eq!(
            read_workspace_path_from(&config),
            Some(PathBuf::from("/docs/Auracle Strategies")),
            "workspace_path is never overwritten once set",
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn persist_preserves_pre_existing_keys() {
        let home = scratch();
        let dir = home.join(".config").join("auracle");
        std::fs::create_dir_all(&dir).unwrap();
        let config = dir.join("auracle.json");
        std::fs::write(
            &config,
            r#"{"engine_url":"http://127.0.0.1:1969","api_key":"secret"}"#,
        )
        .unwrap();

        persist_workspace_path_to(&config, Path::new("/ws")).expect("persist");

        let v: Value = serde_json::from_str(&read(&config)).unwrap();
        assert_eq!(
            v["engine_url"], "http://127.0.0.1:1969",
            "engine_url survives"
        );
        assert_eq!(v["api_key"], "secret", "api_key survives");
        assert_eq!(v["workspace_path"], "/ws");
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn read_workspace_path_absent_is_none() {
        let home = scratch();
        let config = home.join("auracle.json");
        // No file at all.
        assert_eq!(read_workspace_path_from(&config), None);
        // File without the field.
        std::fs::write(&config, r#"{"api_key":"k"}"#).unwrap();
        assert_eq!(read_workspace_path_from(&config), None);
        let _ = std::fs::remove_dir_all(&home);
    }

    // ── test helpers ─────────────────────────────────────────────────────

    /// Sorted list of relative paths under `root` — a stable tree fingerprint.
    fn walk(root: &Path) -> Vec<String> {
        let mut out = Vec::new();
        fn rec(dir: &Path, base: &Path, out: &mut Vec<String>) {
            let mut entries: Vec<_> = std::fs::read_dir(dir)
                .unwrap()
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .collect();
            entries.sort();
            for p in entries {
                out.push(p.strip_prefix(base).unwrap().to_string_lossy().into_owned());
                if p.is_dir() {
                    rec(&p, base, out);
                }
            }
        }
        rec(root, root, &mut out);
        out.sort();
        out
    }

    /// The access mode (`rw` / `ro`) declared for `svc` in a rendered override,
    /// read from the trailing token of its `source:target:mode` mount line.
    fn mode_for(content: &str, svc: &str) -> String {
        let mut lines = content.lines();
        while let Some(line) = lines.next() {
            if line.trim_start() == format!("{svc}:") {
                // next lines: "    volumes:" then "      - \"...\""
                lines.next();
                if let Some(vol) = lines.next() {
                    let mount = vol.trim().trim_start_matches("- ").trim_matches('"');
                    return mount.rsplit(':').next().unwrap_or("").to_string();
                }
            }
        }
        String::new()
    }

    /// Build a service-name set from a slice, for the pure renderer/parser tests.
    fn services_set(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|s| s.to_string()).collect()
    }

    /// Write a minimal but realistic base `docker-compose.yml` into `home` that
    /// declares `services` (2-space keys, 4-space sub-keys, 6-space list items),
    /// so `write_override` exercises the real base-compose read + parse path.
    fn write_base_compose(home: &Path, services: &[&str]) {
        use std::fmt::Write;
        let mut s = String::from("name: auracle\n\nservices:\n");
        for svc in services {
            let _ = writeln!(s, "  {svc}:");
            let _ = writeln!(s, "    image: example/{svc}:latest");
            let _ = writeln!(s, "    volumes:");
            let _ = writeln!(s, "      - ./strategies:/opt/auracle/strategies:rw");
        }
        s.push_str("volumes:\n  db-data:\n");
        std::fs::write(home.join("docker-compose.yml"), s).unwrap();
    }
}
